# Generated by Django 6.0.3 on 2026-03-24 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('SKU', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SKU debe ser alfanumérico', regex='^[a-zA-Z0-9]+$')])),
                ('cantidad', models.PositiveIntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
