# Generated by Django 6.0.3 on 2026-03-24 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='SKU',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SKU debe tener el formato ING-XXXX donde XXXX son dígitos.', regex='^ING-\\d{4}$')]),
        ),
    ]
